argo-cd:
  redis-ha:
    enabled: false

  controller:
    replicas: 1

  repoServer:
    replicas: 2

  applicationSet:
    replicaCount: 2

  server:
    replicas: 3
    additionalProjects: 
    - name: argocd
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      description: Argocd Project
      sourceRepos:
      - '*'
      destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      orphanedResources:
        warn: false

test-1:
  enabled: true