apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-install
  namespace: argocd
spec:
  project: sample-project
  source:
    repoURL: https://github.com/maryamagno-affinity/argocd.git
    targetRevision: HEAD
    path: argocd-install/argo-cd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
