apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    namespace: test-namespace
    server: https://kubernetes.default.svc
  project: sample-project
  source:
    path: applications/sample-app/chart/
    repoURL: https://github.com/maryamagno-affinity/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: {}